base/urls.py
from django.urls import path
from base import views

app_name = 'base'

urlpatterns = [
    path('select_customer_level/', views.select_customer_level, name='select_customer_level'),
    path('datadic_index/', views.datadic_index, name='datadic_index'),
    path('select_datadic/', views.select_datadic, name='select_datadic'),
    path('select_datadic_name/', views.select_datadic_name, name='select_datadic_name'),
    path('create_datadic/', views.create_datadic, name='create_datadic'),
    path('update_datadic/', views.update_datadic, name='update_datadic'),
    path('delete_datadic/', views.delete_datadic, name='delete_datadic'),
    path('product_index/', views.product_index, name='product_index'),
    path('select_product/', views.select_product, name='select_product'),
    path('create_product/', views.create_product, name='create_product'),
    path('update_product/', views.update_product, name='update_product'),
    path('delete_product/', views.delete_product, name='delete_product'),
]

crm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('system/', include('system.urls')),
    path('sales/', include('sales.urls')),
    path('customer/', include('customer.urls')),
    path('base/', include('base.urls')),
    path('serve/', include('serve.urls')),
    path('report/', include('report.urls'))
]

base/models.py
from django.db import models


class ModelManager(models.Manager):
    def get_queryset(self):
        return super(ModelManager, self).get_queryset().filter(isValid=1)


# 数据字典模型
class DataDic(models.Model):
    dataDicName = models.CharField(max_length=50, db_column='data_dic_name')
    dataDicValue = models.CharField(max_length=50, db_column='data_dic_value')
    isValid = models.IntegerField(db_column='is_valid', default=1)
    createDate = models.DateTimeField(db_column='create_date', auto_now_add=True)
    updateDate = models.DateTimeField(db_column='update_date')

    objects = ModelManager()

    class Meta:
        db_table = 't_datadic'


# 产品模型
class Product(models.Model):
    # 产品名称
    productName = models.CharField(max_length=50, db_column='product_name')
    # 型号
    model = models.CharField(max_length=50, db_column='model')
    # 单位
    unit = models.CharField(max_length=15, db_column='unit')
    # 价格
    price = models.FloatField()
    # 库存
    store = models.IntegerField()
    # 备注
    remark = models.CharField(max_length=50, db_column='remark')
    isValid = models.IntegerField(db_column='is_valid', default=1)
    createDate = models.DateTimeField(db_column='create_date', auto_now_add=True)
    updateDate = models.DateTimeField(db_column='update_date')

    objects = ModelManager()

    class Meta:
        db_table = 't_product'

base/views.py
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_GET, require_POST
from base.models import DataDic, Product
from datetime import datetime
from django.db.models import Count


@require_GET
def select_customer_level(request):
    try:
        dic_name = request.GET.get('dic_name')
        res = DataDic.objects.values('dataDicValue').filter(dataDicName=dic_name)
        return JsonResponse(list(res), safe=False)
    except Exception as e:
        return JsonResponse({'code': 400, 'msg': '查询失败'})


def datadic_index(request):
    return render(request, 'base/datadic_index.html')


@require_GET
def select_datadic(request):
    try:
        page_num = request.GET.get('page')
        page_size = request.GET.get('rows')
        ones = DataDic.objects.values().order_by('-dataDicName')
        p = Paginator(ones, page_size)
        data = p.page(page_num).object_list
        context = {
            'total': p.count,
            'rows': list(data)
        }
        return JsonResponse(context)
    except Exception as e:
        return JsonResponse({"code": 400, 'msg': '查询失败'})


@require_GET
def select_datadic_name(request):
    try:
        # ones = DataDic.objects.values('dataDicName').annotate(dn=Count('dataDicName'))
        ones = DataDic.objects.values('dataDicName').distinct()
        return JsonResponse(list(ones), safe=False)
    except Exception as e:
        return JsonResponse({"code": 400, 'msg': '查询失败'})


@csrf_exempt
@require_POST
def create_datadic(request):
    try:
        data = request.POST.dict()
        data.pop('csrfmiddlewaretoken')
        data.pop('id')
        DataDic.objects.create(**data)
        return JsonResponse({"code": 200, 'msg': '创建成功'})

    except Exception as e:
        return JsonResponse({"code": 400, 'msg': '创建失败'})


@csrf_exempt
@require_POST
def update_datadic(request):
    try:
        data = request.POST.dict()
        data.pop('csrfmiddlewaretoken')
        id = data.pop('id')
        data['updateDate'] = datetime.now()
        DataDic.objects.filter(pk=id).update(**data)
        return JsonResponse({"code": 200, 'msg': '更新成功'})
    except Exception as e:
        return JsonResponse({"code": 400, 'msg': '更新失败'})


@require_GET
def delete_datadic(request):
    try:
        ids = request.GET.get('id')
        ids = ids.split(',')
        DataDic.objects.filter(pk__in=ids).update(isValid=0, updateDate=datetime.now())
        # for id in ids:
        # DataDic.objects.filter(pk=int(id)).update(isValid=0, updateDate=datetime.now())
        return JsonResponse({"code": 200, 'msg': '删除成功'})
    except Exception as e:
        return JsonResponse({"code": 400, 'msg': '删除失败'})


def product_index(request):
    return render(request, 'base/product_index.html')


@require_GET
def select_product(request):
    try:
        page_num = request.GET.get('page')
        page_size = request.GET.get('rows')
        ones = Product.objects.values().order_by('-id')
        p = Paginator(ones, page_size)
        data = p.page(page_num).object_list
        context = {
            'total': p.count,
            'rows': list(data)
        }
        return JsonResponse(context)
    except Exception as e:
        return JsonResponse({"code": 400, 'msg': '查询失败'})


# @require_GET
# def select_product_name(request):
#     try:
#         # ones = DataDic.objects.values('dataDicName').annotate(dn=Count('dataDicName'))
#         ones = DataDic.objects.values('dataDicName').distinct()
#         return JsonResponse(list(ones), safe=False)
#     except Exception as e:
#         return JsonResponse({"code": 400, 'msg': '查询失败'})


@csrf_exempt
@require_POST
def create_product(request):
    try:
        data = request.POST.dict()
        data.pop('csrfmiddlewaretoken')
        data.pop('id')
        Product.objects.create(**data)
        return JsonResponse({"code": 200, 'msg': '创建成功'})

    except Exception as e:
        return JsonResponse({"code": 400, 'msg': '创建失败'})


@csrf_exempt
@require_POST
def update_product(request):
    try:
        data = request.POST.dict()
        data.pop('csrfmiddlewaretoken')
        id = data.pop('id')
        data['updateDate'] = datetime.now()
        Product.objects.filter(pk=id).update(**data)
        return JsonResponse({"code": 200, 'msg': '更新成功'})
    except Exception as e:
        return JsonResponse({"code": 400, 'msg': '更新失败'})


@require_GET
def delete_product(request):
    try:
        ids = request.GET.get('id')
        ids = ids.split(',')
        Product.objects.filter(pk__in=ids).update(isValid=0, updateDate=datetime.now())
        # for id in ids:
        # DataDic.objects.filter(pk=int(id)).update(isValid=0, updateDate=datetime.now())
        return JsonResponse({"code": 200, 'msg': '删除成功'})
    except Exception as e:
        return JsonResponse({"code": 400, 'msg': '删除失败'})

templates/base/datadic_index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>数据字典管理</title>
    <link rel="stylesheet" type="text/css" href="{% static '/jquery-easyui-1.3.3/themes/default/easyui.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/jquery-easyui-1.3.3/themes/icon.css' %}">
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/jquery.easyui.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/locale/easyui-lang-zh_CN.js' %}"></script>
    <script type="text/javascript" src="{% static '/js/jquery.cookie.js' %}"></script>
</head>
<body>
<table id="dg" class="easyui-datagrid" title="数据字典管理"
       data-options="rownumbers:true,pagination:true,fit:true,
			    pageList:[10,15,20,30,40,50],toolbar: '#tb',
                url:'{% url 'base:select_datadic' %}',method:'get'">
    <thead>
    <tr>
        <th data-options="field:'id',checkbox:true"></th>
        <th data-options="field:'dataDicName',align:'center',width:548">数据字典名</th>
        <th data-options="field:'dataDicValue',align:'center',width:546">数据字典值</th>
    </tr>
    </thead>
</table>

{# 工具栏 #}
<div id="tb">
    <a onclick="open_datadic_dialog(1);" class="easyui-linkbutton" data-options="iconCls:'icon-add',plain:true">添加</a>
    <a onclick="open_datadic_dialog(2);" class="easyui-linkbutton" data-options="iconCls:'icon-edit',plain:true">修改</a>
    <a onclick="delete_datadic();" class="easyui-linkbutton" data-options="iconCls:'icon-remove',plain:true">删除</a>
</div>

{# 对话框 #}
<div id="dialog" class="easyui-dialog">
    <input type="hidden" id="flag"/>
    <form id="fm" method="post">
        <input type="hidden" id="csrfmiddlewaretoken" name="csrfmiddlewaretoken"/>
        <input type="hidden" id="id" name="id"/>
        <table cellpadding="10px">
            <tr>
                <td style="padding-right: 10px">字典名</td>
                <td>
                    <input id="dataDicName" name="dataDicName" class="easyui-combobox"
                           data-options="valueField:'dataDicName',textField:'dataDicName',editable:true,
                                url:'{% url 'base:select_datadic_name' %}',method:'get'">
                    <span style="color: #ff0000;padding-left: 10px">*</span>
                </td>
                <td style="padding-left: 70px;padding-right: 10px">字典值</td>
                <td><input id="dataDicValue" name="dataDicValue"/><span style="color: red;padding-left: 10px">*</span>
                </td>
            </tr>
        </table>
    </form>
</div>
<script type="text/javascript" src="{% static '/js/base/datadic_index.js' %}"></script>
</body>
</html>

templates/base/product_index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>产品信息管理</title>
    <link rel="stylesheet" type="text/css" href="{% static '/jquery-easyui-1.3.3/themes/default/easyui.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/jquery-easyui-1.3.3/themes/icon.css' %}">
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/jquery.easyui.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/locale/easyui-lang-zh_CN.js' %}"></script>
    <script type="text/javascript" src="{% static '/js/jquery.cookie.js' %}"></script>
</head>
<body>
<table id="dg" class="easyui-datagrid" title="产品信息管理"
       data-options="rownumbers:true,pagination:true,fit:true,
			    pageList:[10,15,20,30,40,50],toolbar: '#tb',
                url:'{% url 'base:select_product' %}',method:'get'">
    <thead>
    <tr>
        <th data-options="field:'id',checkbox:true"></th>
        <th data-options="field:'productName',align:'center',width:300">产品名称</th>
        <th data-options="field:'model',align:'center',width:100">型号</th>
        <th data-options="field:'unit',align:'center',width:50">单位</th>
        <th data-options="field:'price',align:'center',width:100">价格</th>
        <th data-options="field:'store',align:'center',width:100">库存</th>
        <th data-options="field:'remark',align:'center',width:440">备注</th>
    </tr>
    </thead>
</table>

{# 工具栏 #}
<div id="tb">
    <a onclick="open_product_dialog(1);" class="easyui-linkbutton" data-options="iconCls:'icon-add',plain:true">添加</a>
    <a onclick="open_product_dialog(2);" class="easyui-linkbutton" data-options="iconCls:'icon-edit',plain:true">修改</a>
    <a onclick="delete_product();" class="easyui-linkbutton" data-options="iconCls:'icon-remove',plain:true">删除</a>
</div>

{# 对话框 #}
<div id="dialog" class="easyui-dialog">
    <input type="hidden" id="flag"/>
    <form id="fm" method="post">
        <input id="id" name="id" type="hidden"/>
        <input id="csrfmiddlewaretoken" name="csrfmiddlewaretoken" type="hidden"/>
        <table cellspacing="8px">
            <tr>
                <td>产品名称：</td>
                <td><input class="easyui-validatebox" id="productName" name="productName" required="true"/>&nbsp;<font
                        color="red">*</font></td>
                <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <td>型号：</td>
                <td><input type="text" id="model" name="model" class="easyui-validatebox" required="true"/>&nbsp;<font
                        color="red">*</font></td>
            </tr>
            <tr>
                <td>单位：</td>
                <td><input class="easyui-validatebox" id="unit" name="unit" required="true"/>&nbsp;<font
                        color="red">*</font></td>
                <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <td>价格：</td>
                <td><input type="text" id="price" name="price" class="easyui-numberbox" required="true"/>&nbsp;<font
                        color="red">*</font></td>
            </tr>
            <tr>
                <td>库存：</td>
                <td><input class="easyui-numberbox" id="store" name="store" required="true"/>&nbsp;<font
                        color="red">*</font></td>
                <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
                <td>备注：</td>
                <td><input type="text" id="remark" name="remark"/>&nbsp;</td>
            </tr>
        </table>
    </form>
</div>
<script type="text/javascript" src="{% static '/js/base/product_index.js' %}"></script>
</body>
</html>