base/urls.py
from django.urls import path
from base import views

app_name = 'base'

urlpatterns = [
    path('select_customer_level/', views.select_customer_level, name='select_customer_level'),
    path('datadic_index/', views.datadic_index, name='datadic_index'),
    path('select_datadic/', views.select_datadic, name='select_datadic'),
    path('select_datadic_name/', views.select_datadic_name, name='select_datadic_name'),
    path('create_datadic/', views.create_datadic, name='create_datadic'),
    path('update_datadic/', views.update_datadic, name='update_datadic'),
    path('delete_datadic/', views.delete_datadic, name='delete_datadic'),
    path('product_index/', views.product_index, name='product_index'),
    path('select_product/', views.select_product, name='select_product'),
    path('create_product/', views.create_product, name='create_product'),
    path('update_product/', views.update_product, name='update_product'),
    path('delete_product/', views.delete_product, name='delete_product'),
]

crm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('system/', include('system.urls')),
    path('sales/', include('sales.urls')),
    path('customer/', include('customer.urls')),
    path('base/', include('base.urls')),
    path('serve/', include('serve.urls')),
    path('report/', include('report.urls'))
]

customer/urls.py
from django.urls import path
from customer import views

app_name = 'customer'

urlpatterns = [
    path('select_cname_and_lname_and_uname/', views.select_cname_and_lname_and_uname,
         name='select_cname_and_lname_and_uname'),
    path('select_link_phone_by_id/', views.select_link_phone_by_id, name='select_link_phone_by_id'),
    path('customer_index/', views.customer_index, name='customer_index'),
    path('select_customer_list/', views.select_customer_list, name='select_customer_list'),
    path('create_customer/', views.create_customer, name='create_customer'),
    path('select_customer_by_id/', views.select_customer_by_id, name='select_customer_by_id'),
    path('update_customer/', views.update_customer, name='update_customer'),
    path('delete_customer/', views.delete_customer, name='delete_customer'),
    path('linkman_index/', views.linkman_index, name='linkman_index'),
    path('select_linkman_by_customer_id/<int:id>/', views.select_linkman_by_customer_id,
         name='select_linkman_by_customer_id'),
    path('create_linkman/<int:id>/', views.create_linkman, name='create_linkman'),
    path('update_linkman/', views.update_linkman, name='update_linkman'),
    path('delete_linkman/', views.delete_linkman, name='delete_linkman'),
    path('contact_index/', views.contact_index, name='contact_index'),
    path('select_contact_by_customer_id/<int:id>/', views.select_contact_by_customer_id,
         name='select_contact_by_customer_id'),
    path('create_contact/<int:id>/', views.create_contact, name='create_contact'),
    path('update_contact/', views.update_contact, name='update_contact'),
    path('delete_contact/', views.delete_contact, name='delete_contact'),
    path('order_index/', views.order_index, name='order_index'),
    path('select_order_by_customer_id/<int:id>/', views.select_order_by_customer_id,
         name='select_order_by_customer_id'),
    path('select_order_by_id/', views.select_order_by_id, name='select_order_by_id'),
    path('select_order_detail_by_order_id/<int:id>/', views.select_order_detail_by_order_id,
         name='select_order_detail_by_order_id'),
    path('customer_loss_index/', views.customer_loss_index, name='customer_loss_index'),
    path('select_loss/', views.select_loss, name='select_loss'),
    path('reprieve_index/', views.reprieve_index, name='reprieve_index'),
    path('select_reprieve_by_loss_id/<int:id>/', views.select_reprieve_by_loss_id, name='select_reprieve_by_loss_id'),
    path('create_reprieve/<int:id>/', views.create_reprieve, name='create_reprieve'),
    path('update_reprieve/', views.update_reprieve, name='update_reprieve'),
    path('delete_reprieve/', views.delete_reprieve, name='delete_reprieve'),
    path('ok_reprieve/', views.ok_reprieve, name='ok_reprieve'),
    path('select_customer_name/', views.select_customer_name, name='select_customer_name')
]

customer/views.py
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST, require_GET

from crm.common import permission_required
from customer.models import Customer, LinkMan, Contact, CustomerOrders, OrdersDetail, CustomerLoss, CustomerReprieve
from system.models import User
from django.shortcuts import render
from django.core.paginator import Paginator

from datetime import datetime
import random


@require_GET
@permission_required('101001')
def select_cname_and_lname_and_uname(request):
    try:
        us = User.objects.values('id', 'username').all()
        cs = Customer.objects.values('id', 'name').all()
        ls = LinkMan.objects.values('id', 'linkName').all()
        context = {
            'code': 200,
            'cs': list(cs),
            'ls': list(ls),
            'us': list(us)
        }

        return JsonResponse(context)
    except Exception as e:
        return JsonResponse({'code': 400, 'msg': '打开失败'})


@require_GET
def select_link_phone_by_id(request):
    try:
        id = request.GET.get('id')
        cus = Customer.objects.values('phone').get(id=id)
        return JsonResponse({'code': 200, 'phone': cus['phone']})
    except Customer.DoesNotExist as e:
        return JsonResponse({'code': 400, 'msg': '用戶不存在'})


def customer_index(request):
    return render(request, 'customer/customer.html')


@require_GET
def select_customer_list(request):
    try:
        page_num = request.GET.get('page')
        page_size = request.GET.get('rows')
        name = request.GET.get('name')
        khno = request.GET.get('khno')
        state = request.GET.get('state')
        ones = Customer.objects.all().values()
        if name:
            ones = ones.filter(name__contains=name)
        if khno:
            ones = ones.filter(khno__contains=khno)
        if state:
            ones = ones.filter(state=state)
        p = Paginator(list(ones), page_size)
        data = p.page(page_num).object_list

        context = {
            'total': p.count,
            'rows': data
        }
        return JsonResponse(context)
    except Exception as e:
        return JsonResponse({'code': 400, 'msg': '查询失败'})


@csrf_exempt
@require_POST
def create_customer(request):
    try:
        data = request.POST.dict()
        # 生成客户编号
        data['khno'] = 'HK' + datetime.now().strftime('%Y%m%d%H%M%S') + str(random.randint(100, 999))
        Customer.objects.create(**data)
        return JsonResponse({'code': 200, 'msg': '添加成功'})
    except Exception as e:
        return JsonResponse({'code': 400, 'msg': '添加失败'})


@require_GET
def select_customer_by_id(request):
    try:
        id = request.GET.get('id')
        one = Customer.objects.values().get(pk=id)
        return JsonResponse({'code': 200, 'obj': one})
    except Customer.DoesNotExist as e:
        return JsonResponse({'code': 400, 'msg': '查找失败'})


# @csrf_exempt
@require_POST
def update_customer(request):
    try:
        data = request.POST.dict()
        data.pop('csrfmiddlewaretoken')
        id = data.pop('id')
        data['updateDate'] = datetime.now()
        Customer.objects.filter(pk=id).update(**data)
        return JsonResponse({'code': 200, 'msg': '更新成功'})
    except Exception as e:
        return JsonResponse({'code': 400, 'msg': '更新失败'})


@require_GET
def delete_customer(request):
    try:
        ids = request.GET.get('ids')
        for id in ids.split(','):
            Customer.objects.filter(pk=id).update(isValid=0)
        return JsonResponse({'code': 200, 'msg': '删除成功'})
    except Exception as e:
        return JsonResponse({'code': 400, 'msg': '删除失败'})


@require_GET
def linkman_index(request):
    try:
        id = request.GET.get('id')
        one = Customer.objects.values('id', 'khno', 'name').get(id=id)
        return render(request, 'customer/linkman.html', {'c': one})
    except Customer.DoesNotExist as e:
        return JsonResponse({'code': 400, 'msg': '查找失败'})


@csrf_exempt
@require_POST
def select_linkman_by_customer_id(request, id):
    try:
        page_num = request.POST.get('page')
        page_size = request.POST.get('rows')
        object_list = LinkMan.objects.values().filter(customer_id=id).order_by('-id')
        p = Paginator(object_list, page_size)
        data = p.page(page_num).object_list

        context = {
            'total': p.count,
            'rows': list(data)
        }
        return JsonResponse(context)
    except LinkMan.DoesNotExist as e:
        return JsonResponse({'code': 400, 'msg': '查找失败'})


@csrf_exempt
@require_POST
def create_linkman(request, id):
    try:
        data = request.POST.dict()
        data.pop('isNewRecord')
        c = Customer.objects.get(pk=id)
        data['customer'] = c
        LinkMan.objects.create(**data)
        return JsonResponse({'code': 200, 'msg': '创建成功'})
    except Exception as e:
        return JsonResponse({'code': 400, 'msg': '创建失败'})


@csrf_exempt
@require_POST
def update_linkman(request):
    try:
        data = request.POST.dict()
        id = data.pop('id')
        data['updateDate'] = datetime.now()
        LinkMan.objects.filter(pk=id).update(**data)
        return JsonResponse({'code': 200, 'msg': '更新成功'})
    except Exception as e:
        return JsonResponse({'code': 400, 'msg': '更新失败'})


@csrf_exempt
@require_POST
def delete_linkman(request):
    try:
        id = request.POST.get('id')
        LinkMan.objects.filter(pk=id).update(isValid=0, updateDate=datetime.now())
        return JsonResponse({'code': 200, 'msg': '删除成功'})
    except Exception as e:
        return JsonResponse({'code': 400, 'msg': '删除失败'})


@require_GET
def contact_index(request):
    try:
        id = request.GET.get('id')
        one = Customer.objects.values('id', 'khno', 'name').get(pk=id)
        return render(request, 'customer/contact.html', {'c': one})
    except Customer.DoesNotExist as e:
        return JsonResponse({'code': 400, 'msg': '查找失败'})


@csrf_exempt
@require_POST
def select_contact_by_customer_id(request, id):
    try:
        page_num = request.POST.get('page')
        page_size = request.POST.get('rows')
        ones = Contact.objects.values().filter(customer_id=id).order_by('-id')
        p = Paginator(ones, page_size)
        data = p.page(page_num).object_list
        context = {
            'total': p.count,
            'rows': list(data)
        }
        return JsonResponse(context)
    except Exception as e:
        return JsonResponse({'code': 400, 'msg': '查询失败'})


@csrf_exempt
@require_POST
def create_contact(request, id):
    try:
        data = request.POST.dict()
        data.pop('isNewRecord')
        c = Customer.objects.get(pk=id)
        data['customer'] = c
        print(data)
        Contact.objects.create(**data)
        return JsonResponse({'code': 200, 'msg': '创建成功'})
    except Exception as e:
        return JsonResponse({'code': 400, 'msg': '创建失败'})


@csrf_exempt
@require_POST
def update_contact(request):
    try:
        data = request.POST.dict()
        id = data.pop('id')
        data['updateDate'] = datetime.now()
        Contact.objects.filter(pk=id).update(**data)
        return JsonResponse({'code': 200, 'msg': '更新成功'})
    except Exception as e:
        return JsonResponse({'code': 400, 'msg': '更新失败'})


@csrf_exempt
@require_POST
def delete_contact(request):
    try:
        id = request.POST.get('id')
        Contact.objects.filter(pk=id).update(isValid=0, updateDate=datetime.now())
        return JsonResponse({'code': 200, 'msg': '删除成功'})
    except Exception as e:
        return JsonResponse({'code': 400, 'msg': '删除失败'})


@require_GET
def order_index(request):
    id = request.GET.get('id')
    c = Customer.objects.values('id', 'name', 'khno').get(pk=id)
    return render(request, 'customer/order.html', {'c': c})


@csrf_exempt
@require_POST
def select_order_by_customer_id(request, id):
    try:
        page_num = request.POST.get('page')
        page_size = request.POST.get('rows')
        ones = CustomerOrders.objects.values().filter(customer_id=id).order_by('-id')
        p = Paginator(ones, page_size)
        data = p.page(page_num).object_list

        context = {
            'total': p.count,
            'rows': list(data)
        }
        return JsonResponse(context)
    except Exception as e:
        return JsonResponse({'code': 400, 'msg': '查询失败'})


@require_GET
def select_order_by_id(request):
    try:
        id = request.GET.get('order_id')
        one = CustomerOrders.objects.values().get(pk=id)
        return JsonResponse({'code': 200, 'obj': one})
    except Exception as e:
        return JsonResponse({'code': 400, 'msg': '查询失败'})


@csrf_exempt
@require_POST
def select_order_detail_by_order_id(request, id):
    try:
        page_num = request.POST.get('page')  # 第几页
        page_size = request.POST.get('rows')  # 每页多少个
        ones = OrdersDetail.objects.values().filter(order_id=id).order_by('-id')
        p = Paginator(ones, page_size)
        data = p.page(page_num).object_list

        context = {
            'total': p.count,
            'rows': list(data)
        }
        return JsonResponse(context)
    except Exception as e:
        return JsonResponse({'code': 400, 'msg': '查询失败'})


def customer_loss_index(request):
    return render(request, 'customer/loss.html')


@require_GET
def select_loss(reqeust):
    try:
        cusName = reqeust.GET.get('cusName')
        cusManager = reqeust.GET.get('cusManager')
        state = reqeust.GET.get('state')
        page_num = reqeust.GET.get('page')
        page_size = reqeust.GET.get('rows')
        ones = CustomerLoss.objects.values().all().order_by('-id')
        if cusName:
            ones = ones.filter(cusName__contains=cusName)
        if cusManager:
            ones = ones.filter(cusManager__contains=cusManager)
        if state:
            ones = ones.filter(state=state)
        p = Paginator(ones, page_size)
        data = p.page(page_num).object_list

templates/customer/contact.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>客户交往记录管理</title>
    <link rel="stylesheet" type="text/css" href="{% static '/jquery-easyui-1.3.3/themes/default/easyui.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/jquery-easyui-1.3.3/themes/icon.css' %}">
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/jquery.easyui.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/locale/easyui-lang-zh_CN.js' %}"></script>
    <script type="text/javascript" src="{% static "/jquery-easyui-1.3.3/jquery.edatagrid.js" %}"></script>
</head>
<body>
<input type="hidden" id="id" value="{{ c.id }}"/>
{# 客户信息展示 #}
<div id="p" class="easyui-panel" title="客户基本信息"
     style="width:600px;height:150px;padding:10px;background:#fafafa;"
     data-options="iconCls:'icon-save',closable:true,
                collapsible:true,minimizable:false,closable:false,maximizable:true">
    <br/><br/>
    <label style="padding-right: 10px;padding-left: 50px">客户编号</label><input readonly value="{{ c.khno }}"/>
    <label style="padding-right: 10px;padding-left: 10px">客户名称</label><input readonly value="{{ c.name }}"/>
</div>

{# 联系人信息展示 #}
<table id="tt" style="width:600px;height:333px" class="easyui-datagrid"
       title="交往记录管理" toolbar="#tb"
       singleSelect="true">
    <thead>
    <tr>
        <th field="id" width="30">编号</th>

        <th field="contactTime" width="150" formatter="formatter_datetime"
            editor="{type:'datebox',options:{required:true}}">交往时间
        </th>
        <th field="address" width="180" editor="{type:'validatebox',options:{required:true}}">交往地址</th>
        <th field="overview" width="200" editor="{type:'validatebox',options:{required:true}}">概要</th>
    </tr>
    </thead>
</table>

{# 工具栏 #}
<div id="tb">
    <a onclick="add();" class="easyui-linkbutton" data-options="iconCls:'icon-add',plain:true">添加</a>
    <a onclick="cancel();" class="easyui-linkbutton" data-options="iconCls:'icon-undo',plain:true">取消</a>
    <a onclick="save();" class="easyui-linkbutton" data-options="iconCls:'icon-save',plain:true">保存</a>
    <a onclick="destroy();" class="easyui-linkbutton" data-options="iconCls:'icon-remove',plain:true">删除</a>
</div>
<script type="text/javascript" src="{% static '/js/customer/contact.js' %}"></script>
</body>
</html>

templates/customer/customer.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>客户信息管理</title>
    <link rel="stylesheet" type="text/css" href="{% static '/jquery-easyui-1.3.3/themes/default/easyui.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/jquery-easyui-1.3.3/themes/icon.css' %}">
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/jquery.easyui.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/locale/easyui-lang-zh_CN.js' %}"></script>
</head>
<body>
<div style="margin:5px 0;"></div>
<table id="dg" class="easyui-datagrid" title="客户信息管理"
       data-options="rownumbers:true,pagination:true,fit:true,
			    pageList:[10,15,20,30,40,50],toolbar: '#tb',
                url:'{% url 'customer:select_customer_list' %}',method:'get'">
    <thead data-options="frozen:true">
    <tr>
        <th data-options="field:'id',checkbox:true"></th>
        <th data-options="field:'khno',width:150">客户编号</th>
        <th data-options="field:'name',width:180">客户名称</th>
        <th data-options="field:'cusManager',width:100">客户经理</th>
        <th data-options="field:'level',width:90">客户等级</th>
        <th data-options="field:'phone',width:100">联系电话</th>
    </tr>
    </thead>
    <thead>
    <tr>
        <th data-options="field:'area',width:60">客户地区</th>
        <th data-options="field:'myd',width:60">满意度</th>
        <th data-options="field:'xyd',width:60">信用度</th>
        <th data-options="field:'address',width:150">地址</th>
        <th data-options="field:'postCode',width:60">邮编</th>
        <th data-options="field:'fax',width:80">传真</th>
        <th data-options="field:'website',width:120">网址</th>
        <th data-options="field:'yyzzzch',width:150">营业注册号</th>
        <th data-options="field:'fr',width:80">法人</th>
        <th data-options="field:'zczj',width:80">注册资金</th>
        <th data-options="field:'nyye',width:150">年营业额</th>
        <th data-options="field:'khyh',width:60">开户银行</th>
        <th data-options="field:'khzh',width:150">开户账号</th>
        <th data-options="field:'dsdjh',width:80">地税</th>
        <th data-options="field:'gsdjh',width:80">国税</th>
        <th data-options="field:'state',width:80,formatter:formatter_state">状态</th>
        <th data-options="field:'createDate',width:150,formatter:formatter_datetime">创建时间</th>
        <th data-options="field:'updateDate',width:150,formatter:formatter_datetime">修改时间</th>
    </tr>
    </thead>
</table>

{# 工具栏 #}
<div id="tb">
    <a onclick="open_customer_create_dialog();" class="easyui-linkbutton"
       data-options="iconCls:'icon-add',plain:true">添加</a>
    <a onclick="open_customer_update_dialog();" class="easyui-linkbutton"
       data-options="iconCls:'icon-edit',plain:true">修改</a>
    <a onclick="delete_customer();" class="easyui-linkbutton" data-options="iconCls:'icon-remove',plain:true">删除</a>
    <a onclick="open_linkman_window();" class="easyui-linkbutton"
       data-options="iconCls:'icon-lxr',plain:true">联系人管理</a>
    <a onclick="open_contact_window();" class="easyui-linkbutton"
       data-options="iconCls:'icon-jwjl',plain:true">交往记录管理</a>
    <a onclick="open_order_window();" class="easyui-linkbutton" data-options="iconCls:'icon-lsdd',plain:true">历史订单查看</a>
    <div>
        &nbsp;&nbsp;客户名称&nbsp;&nbsp;<input id="customer_name" onkeydown="if (event.keyCode==13) select_params_customer();"/>
        &nbsp;&nbsp;客户编号&nbsp;&nbsp;<input id="customer_khno" onkeydown="if (event.keyCode==13) select_params_customer();"/>
        &nbsp;&nbsp;状态&nbsp;&nbsp;
        <select class="easyui-combobox" id="customer_state" style="width: 100px">
            <option value="">全部</option>
            <option value="0">正常</option>
            <option value="1">暂时流失</option>
            <option value="2">确认流失</option>
        </select>&nbsp;&nbsp;
        <a id="btn" onclick="select_params_customer();" class="easyui-linkbutton"
           data-options="iconCls:'icon-search'">查询</a>
    </div>
</div>
<input type="hidden" id="flag"/>
<div id="customer_dialog" class="easyui-dialog">
    <form id="customer_form" method="post">
        <input type="hidden" id="csrfmiddlewaretoken" name="csrfmiddlewaretoken"/>
        <input type="hidden" id="id" name="id"/>
        <input type="hidden" id="khno" name="khno"/>
        <table cellpadding="5px">
            <tr>
                <td style="padding-right: 10px">客户名称</td>
                <td>
                    <input id="name" name="name" class="easyui-validatebox" data-options="required:true"/>
                    <span style="color: red;padding-left: 10px">*</span>
                </td>
                <td style="padding-left: 50px;">地区</td>
                <td>
                    <select id="area" name="area" class="easyui-combobox" style="width: 170px">
                        <option value="">请选择地区</option>
                        <option value="北京">北京</option>
                        <option value="上海">上海</option>
                        <option value="广州">广州</option>
                        <option value="深圳">深圳</option>
                        <option value="杭州">杭州</option>
                    </select><span style="color: red;padding-left: 10px">*</span>
                </td>
            </tr>
            <tr>
                <td style="padding-right: 10px">客户经理</td>
                <td>
                    <input id="cusManager" name="cusManager"/><span style="color: red;padding-left: 10px">*</span>
                </td>
                <td style="padding-left: 50px;">客户等级</td>
                <td>
                    <input id="level" name="level" class="easyui-combobox"
                           data-options="valueField:'dataDicValue',textField:'dataDicValue',value:'请选择客户等级',editable:false,
                                url:'{% url 'base:select_customer_level' %}?dic_name=客户等级',method:'get'">
                    <span style="color: red;padding-left: 10px">*</span>
                </td>
            </tr>
            <tr>
                <td>客户满意度</td>
                <td>
                    <select id="myd" name="myd" class="easyui-combobox" style="width: 170px">
                        <option value="">请选择客户满意度</option>
                        <option value="☆">☆</option>
                        <option value="☆☆">☆☆</option>
                        <option value="☆☆☆">☆☆☆</option>
                        <option value="☆☆☆☆">☆☆☆☆</option>
                        <option value="☆☆☆☆☆">☆☆☆☆☆</option>
                    </select>
                    <span style="color: red;padding-left: 10px">*</span>
                </td>
                <td style="padding-left: 50px">客户信用度</td>
                <td>
                    <select id="xyd" name="xyd" class="easyui-combobox" style="width: 170px">
                        <option value="">请选择客户信用度</option>
                        <option value="☆">☆</option>
                        <option value="☆☆">☆☆</option>
                        <option value="☆☆☆">☆☆☆</option>
                        <option value="☆☆☆☆">☆☆☆☆</option>
                        <option value="☆☆☆☆☆">☆☆☆☆☆</option>
                    </select>
                    <span style="color: red;padding-left: 10px">*</span>
                </td>
            </tr>
            <tr>
                <td style="padding-right: 10px">邮政编码</td>
                <td><input id="postCode" name="postCode"/><span style="color: red;padding-left: 10px">*</span></td>
                <td style="padding-left: 50px">联系电话</td>
                <td><input id="phone" name="phone"/><span style="color: red;padding-left: 10px">*</span></td>
            </tr>
            <tr>
                <td style="padding-right: 10px">传真</td>
                <td><input id="fax" name="fax"/><span style="color: red;padding-left: 10px">*</span></td>
                <td style="padding-left: 50px">网址</td>
                <td><input id="website" name="website"/><span style="color: red;padding-left: 10px">*</span></td>
            </tr>
            <tr>
                <td style="padding-right: 10px">客户地址</td>
                <td colspan="3"><input id="address" name="address" style="width: 496px;"/><span style="color: red;padding-left: 10px">*</span></td>
            </tr>
            <tr>
                <td style="padding-right: 10px">营业执照注册号</td>
                <td><input id="yyzzzch" name="yyzzzch"/></td>
                <td style="padding-left: 50px">法人</td>
                <td><input id="fr" name="fr"/><span style="color: red;padding-left: 10px">*</span></td>
            </tr>
            <tr>
                <td style="padding-right: 10px">注册资金(万元)</td>
                <td><input id="zczj" name="zczj"/></td>
                <td style="padding-left: 50px">年营业额</td>
                <td><input id="nyye" name="nyye"/><span style="color: red;padding-left: 10px">*</span></td>
            </tr>
            <tr>
                <td style="padding-right: 10px">开户银行</td>
                <td><input id="khyh" name="khyh" /><span style="color: red;padding-left: 10px">*</span></td>
                <td style="padding-left: 50px">开户账号</td>
                <td><input id="khzh" name="khzh" /><span style="color: red;padding-left: 10px">*</span></td>
            </tr>
            <tr>
                <td style="padding-right: 10px">地税登记号</td>
                <td><input id="dsdjh" name="dsdjh"/></td>
                <td style="padding-left: 50px">国税登记号</td>
                <td><input id="gsdjh" name="gsdjh"/></td>
            </tr>
        </table>
    </form>
</div>

</body>
<script type="text/javascript" src="{% static '/js/jquery.cookie.js' %}"></script>
<script type="text/javascript" src="{% static '/js/customer/customer.js' %}"></script>
</html>

templates/customer/loss.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>客户流失管理</title>
    <link rel="stylesheet" type="text/css" href="{% static '/jquery-easyui-1.3.3/themes/default/easyui.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/jquery-easyui-1.3.3/themes/icon.css' %}">
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/jquery.easyui.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/locale/easyui-lang-zh_CN.js' %}"></script>
    <script type="text/javascript" src="{% static '/js/jquery.cookie.js' %}"></script>
</head>
<body>
<div style="margin:5px 0;"></div>
<table id="dg" class="easyui-datagrid" title="客户流失管理"
       data-options="rownumbers:true,pagination:true,fit:true,
			    pageList:[10,15,20,30,40,50],toolbar: '#tb',
                url:'{% url 'customer:select_loss' %}',method:'get'">
    <thead>
    <tr>
        <th data-options="field:'id',checkbox:true"></th>
        <th data-options="field:'cusNo',width:150">客户编号</th>
        <th data-options="field:'cusName',width:180">客户名称</th>
        <th data-options="field:'cusManager',width:100">客户经理</th>
        <th data-options="field:'lastOrderTime',width:150,formatter:formatter_datetime">上次下单时间</th>
        <th data-options="field:'confirmLossTime',width:150,formatter:formatter_datetime">确认流失时间</th>
        <th data-options="field:'state',width:80,formatter:formatter_state">客户状态</th>
        <th data-options="field:'lossReason',width:180">流失原因</th>
        <th data-options="field:'handler',width:80,formatter:handler">操作</th>
    </tr>
    </thead>
</table>

{# 工具栏 #}
<input type="hidden" id="type" value="c"/>
<div id="tb">
    <div>
        &nbsp;&nbsp;客户名称&nbsp;&nbsp;<input id="cusName" onkeydown="if (event.keyCode==13) select_params_loss('c');"/>
        &nbsp;&nbsp;客户经理&nbsp;&nbsp;<input id="cusManager" onkeydown="if (event.keyCode==13) select_params_loss('c');"/>
        &nbsp;&nbsp;状态&nbsp;&nbsp;
        <select class="easyui-combobox" id="state" style="width: 100px">
            <option value="">全部</option>
            <option value="0">暂时流失</option>
            <option value="1">确认流失</option>
        </select>&nbsp;&nbsp;
        <a id="btn" onclick="select_params_loss('c');" class="easyui-linkbutton"
           data-options="iconCls:'icon-search'">查询</a>
    </div>
</div>
<script type="text/javascript" src="{% static '/js/customer/loss.js' %}"></script>
</body>
</html>