base/urls.py
from django.urls import path
from base import views

app_name = 'base'

urlpatterns = [
    path('select_customer_level/', views.select_customer_level, name='select_customer_level'),
    path('datadic_index/', views.datadic_index, name='datadic_index'),
    path('select_datadic/', views.select_datadic, name='select_datadic'),
    path('select_datadic_name/', views.select_datadic_name, name='select_datadic_name'),
    path('create_datadic/', views.create_datadic, name='create_datadic'),
    path('update_datadic/', views.update_datadic, name='update_datadic'),
    path('delete_datadic/', views.delete_datadic, name='delete_datadic'),
    path('product_index/', views.product_index, name='product_index'),
    path('select_product/', views.select_product, name='select_product'),
    path('create_product/', views.create_product, name='create_product'),
    path('update_product/', views.update_product, name='update_product'),
    path('delete_product/', views.delete_product, name='delete_product'),
]

crm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('system/', include('system.urls')),
    path('sales/', include('sales.urls')),
    path('customer/', include('customer.urls')),
    path('base/', include('base.urls')),
    path('serve/', include('serve.urls')),
    path('report/', include('report.urls'))
]

report/urls.py
from django.urls import path, include
from report import views

app_name = 'report'

urlpatterns = [
    path('report_index/<str:rr>/', views.report_index, name='report_index'),
    path('select_contirbute/', views.select_contirbute, name='select_contirbute'),
    path('select_compostion/', views.select_compostion, name='select_compostion'),
    path('select_serve/', views.select_serve, name='select_serve')
]

sales/urls.py
from django.urls import path
from sales import views

app_name = 'sales'

urlpatterns = [
    path('sale_chance_index/', views.sale_chance_index, name='sale_chance_index'),
    path('select_sale_chance_list/', views.select_sale_chance_list, name='select_sale_chance_list'),
    path('create_sale_chance/', views.create_sale_chance, name='create_sale_chance'),
    path('update_sale_chance/', views.update_sale_chance, name='update_sale_chance'),
    path('select_sale_chance_by_id/', views.select_sale_chance_by_id, name='select_sale_chance_by_id'),
    path('delete_sale_chance/', views.delete_sale_chance, name='delete_sale_chance'),
    path('cus_dev_plan_index/', views.cus_dev_plan_index, name='cus_dev_plan_index'),
    path('select_cus_dev_plan_list/', views.select_cus_dev_plan_list, name='select_cus_dev_plan_list'),
    path('select_sale_chance_by_id_for_page/', views.select_sale_chance_by_id_for_page,
         name='select_sale_chance_by_id_for_page'),
    path('select_cus_dev_plan_by_sale_chance_id/<int:sale_chance_id>/', views.select_cus_dev_plan_by_sale_chance_id,
         name='select_cus_dev_plan_by_sale_chance_id'),
    path('create_cus_dev_plan/<int:sale_chance_id>/', views.create_cus_dev_plan, name='create_cus_dev_plan'),
    path('update_cus_dev_plan/', views.update_cus_dev_plan, name='update_cus_dev_plan'),
    path('delete_cus_dev_plan/', views.delete_cus_dev_plan, name='delete_cus_dev_plan'),
    path('update_dev_result/', views.update_dev_result, name='update_dev_result')
]

serve/urls.py
from django.urls import path
from serve import views

app_name = 'serve'

urlpatterns = [
    path('serve_index/<str:serve_type>/', views.serve_index, name='serve_index'),
    # path('serve_assign/', views.serve_assign, name='serve_assign'),
    # path('serve_handler/', views.serve_handler, name='serve_handler'),
    # path('serve_feedback/', views.serve_feedback, name='serve_feedback'),
    # path('serve_file/', views.serve_file, name='serve_file'),
    path('create_serve/', views.create_serve, name='create_serve'),
    path('select_serve/', views.select_serve, name='select_serve'),
    path('update_serve/', views.update_serve, name='update_serve'),
]

system/urls.py
from django.urls import path
from system import views

app_name = 'system'

urlpatterns = [
    path('login_register/', views.login_register, name='login_register'),
    path('unique_username/', views.unique_username, name='unique_username'),
    path('unique_email/', views.unique_email, name='unique_email'),
    path('send_email/', views.send_email, name='send_email'),
    path('active_account/', views.active_account, name='active_account'),
    path('login_user/', views.login_user, name='login_user'),
    path('index/', views.index, name='index'),
    path('update_password/', views.update_password, name='update_password'),
    path('logout/', views.logout, name='logout'),
    path('select_customer_manager/', views.select_customer_manager, name='select_customer_manager'),
    path('module_index/', views.module_index, name='module_index'),
    path('select_module_by_grade/', views.select_module_by_grade, name='select_module_by_grade'),
    path('update_module/', views.update_module, name='update_module'),
    path('select_module/', views.select_module, name='select_module'),
    path('create_module/', views.create_module, name='create_module'),
    path('delete_module/', views.delete_module, name='delete_module'),
    path('role_index/', views.role_index, name='role_index'),
    path('update_role/', views.update_role, name='update_role'),
    path('select_role/', views.select_role, name='select_role'),
    path('create_role/', views.create_role, name='create_role'),
    path('delete_role/', views.delete_role, name='delete_role'),
    path('role_module_index/', views.role_module_index, name='role_module_index'),
    path('role_relate_module/', views.role_relate_module, name='role_relate_module'),
    path('role_relate_module/', views.role_relate_module, name='role_relate_module'),
    path('user_index/', views.user_index, name='user_index'),
    path('select_user/', views.select_user, name='select_user'),
    path('select_role_for_user/', views.select_role_for_user, name='select_role_for_user'),
    path('create_user/', views.create_user, name='create_user'),
    path('select_role_by_userid/', views.select_role_by_userid, name='select_role_by_userid'),
    path('update_user/', views.update_user, name='update_user'),
    path('delete_user/', views.delete_user, name='delete_user'),
]

system/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST, require_GET
from django.db import transaction
from django.db.models import F

from email.header import Header
from email.mime.text import MIMEText
from email.utils import parseaddr, formataddr
from datetime import datetime, timedelta
from hashlib import md5
import smtplib
import uuid
import base64

from system.models import User, Role, UserRole, Module, Permission


def login_register(request):
    return render(request, 'login_register.html')


@require_POST
def unique_username(request):
    try:
        username = request.POST.get('username')
        user = User.objects.get(username=username)
        return JsonResponse({'code': 400, 'msg': '该用户已存在'})
    except User.DoesNotExist:
        return JsonResponse({'code': 200, 'msg': '恭喜你，用户名可以注册'})


@require_POST
def unique_email(request):
    try:
        email = request.POST.get('email')
        user = User.objects.get(email=email)
        return JsonResponse({'code': 400, 'msg': '该邮箱已注册'})
    except User.DoesNotExist:
        return JsonResponse({'code': 200, 'msg': '恭喜你，邮箱可以注册'})


def format_addr(s):
    name, addr = parseaddr(s)
    return formataddr((Header(name, 'utf-8').encode('utf-8'), addr))


@require_POST
def send_email(request):
    try:
        from_addr = '17625212308@163.com'
        # 邮箱授权码
        from_pwd = 'NVWHTBVDDPRDAFCN'
        smtp_server = 'smtp.163.com'
        to_addr = request.POST.get('email')

        # 激活码
        code = ''.join(str(uuid.uuid4()).split('-'))
        # 10min后的时间戳
        tt = datetime.now() + timedelta(minutes=10)
        ts = str(tt.timestamp()).split('.')[0]

        to_name = request.POST.get('username')
        pd = request.POST.get('password')
        # 使用md5加密
        password = md5(pd.encode(encoding='utf-8')).hexdigest()

        html = """
            <html>
                <body>
                    <a href='http://127.0.0.1:8000/system/active_account/?username={}&code={}&timestamp={}'>点击注册</a>
                </body>
            </html>
        """.format(to_name, code, ts)
        msg = MIMEText(html, 'html', 'utf-8')

        msg['From'] = format_addr(f'诚本地<{from_addr}>')
        msg['To'] = format_addr(f'{to_name}<{to_addr}>')
        msg['Subject'] = Header(u'本地CRM', 'utf-8').encode()

        with transaction.atomic():
            user = User.objects.create(username=to_name, password=password, email=to_addr, code=code, timestamp=ts)
            user.save()
            server = smtplib.SMTP(smtp_server, 25)
            server.set_debuglevel(1)
            server.login(from_addr, from_pwd)
            server.sendmail(from_addr, [to_addr], msg.as_string())
            server.quit()
            return JsonResponse({'code': 200, 'msg': '注册成功，请前往邮箱激活账号'})
    except smtplib.SMTPException as e:
        return JsonResponse({'code': 400, 'msg': '注册失败，请重新注册'})


@require_GET
def active_account(request):
    try:
        username = request.GET.get('username')
        code = request.GET.get('code')
        timestamp = request.GET.get('timestamp')

        user = User.objects.get(username=username, code=code, timestamp=timestamp)

        if int(str(datetime.now().timestamp()).split('.')[0]) < int(timestamp):
            user.code = ''
            user.status = 1  # 有效账号
            user.save()
            return HttpResponse('<h1>激活成功，请<a href="http://127.0.0.1:8000/system/login_register/">前往登录</a></h1>')
        else:
            user.delete()
            # return JsonResponse({'ret': 400, 'msg': '链接失效，请重新注册'})
            return HttpResponse('<h1>链接失效，请<a href="http://127.0.0.1:8000/system/login_register/">重新注册</a></h1>')
    except Exception as e:
        if isinstance(User.DoesNotExist, e):
            return HttpResponse('<h1>激活失败，请<a href="http://127.0.0.1:8000/system/login_register/">重新注册</a></h1>')
        return HttpResponse('网络波动，激活失败，请<a href="http://127.0.0.1:8000/system/login_register/">重新注册</a></h1>')


# 登录
@require_POST
def login_user(request):
    # try:
    #     del request.session['username_session']
    #     del request.session['user_permission']
    # except Exception as e:
    #     pass

    try:
        username = request.POST.get('username')
        pd = request.POST.get('password')
        remember = request.POST.get('remember')

        password = md5(pd.encode(encoding='utf-8')).hexdigest()

        user = User.objects.get(username=username, password=password)

        username_session = request.session.get('username_session')
        # 如果用户存在，存储session信息
        if not username_session:
            request.session['username_session'] = username

            # 设置失效时间,关闭浏览器失效
            request.session.set_expiry(0)

        # 如果用户存在，则根据用户查角色权限
        # roleId = UserRole.objects.values_list('role_id', flat=True).filter(user_id=user.id)
        # roleId = user.roles.values_list('id', flat=True).all()
        # user_permission = Permission.objects.filter(role_id__in=list(roleId)).values_list('module__optValue')
        # permission_session = request.session.get('user_permission')
        # if permission_session is None:
        #     request.session['user_permission'] = list(user_permission)
        #     request.session.set_expiry(0)
        context = {
            'code': 200,
            'msg': '欢迎回来'
        }

        # 如果用户存在，前台js存储cookie
        if remember == 'true':
            context['login_cookie'] = base64.b64encode((username + '&' + pd).encode(encoding='utf-8')).decode(
                encoding='utf-8')

        return JsonResponse(context)
    except User.DoesNotExist as e:
        return JsonResponse({'code': 400, 'msg': '用户名或密码错误'})


# 跳转首页
def index(request):
    # 判断session中是否有用户信息
    username = request.session.get('username_session')

    if username:
        return render(request, 'system/index.html')
    return redirect('system:login_register')


# 修改密码
@require_POST
def update_password(request):
    try:
        username = request.POST.get('username')
        old_password = request.POST.get('old_password')
        new_password = request.POST.get('new_password')

        old_pd = md5(old_password.encode(encoding='utf-8')).hexdigest()
        user = User.objects.get(username=username, password=old_pd)

        new_pd = md5(new_password.encode(encoding='utf-8')).hexdigest()
        user.password = new_pd
        user.save()

        return JsonResponse({'code': 200, 'msg': '修改成功'})
    except User.DoesNotExist as e:
        return JsonResponse({'code': 400, 'msg': '原密码输入错误'})


# 安全退出
def logout(request):
    try:
        # 清除session
        request.session.flush()
        return redirect('system:login_register')
    except Exception as e:
        return redirect('system:login_register')


@require_GET
def select_customer_manager(request):
    try:
        # ones = Role.objects.values('id').filter(roleName__exact='客户经理')
        # id = list(ones)[0]['id']
        names = UserRole.objects.annotate(username=F('user__username')).values('username').filter(
            role__roleName__exact='客户经理')
        # Role.objects.values('username').filter(userrole=id)
        return JsonResponse(list(names), safe=False)
    except Exception as e:
        return JsonResponse({'code': 400, 'msg': '查询失败'})


def module_index(request):
    return render(request, 'system/module.html')


@require_GET
def select_module(request):
    try:
        page_num = request.GET.get('page')
        page_size = request.GET.get('rows')
        ones = Module.objects.values().order_by('grade')
        # {'模型属性名': 'select DATE_FORMAT(数据库列名, '格式化样式')'}
        # select = {'createDate': "select DATE_FORMAT(create_date, '%%Y-%%m-%%d %%H:%%i:%%s')",
        #           'updateDate': "select DATE_FORMAT(update_date, '%%Y-%%m-%%d %%H:%%i:%%s')"}
        # ones = Module.objects.extra(select=select).values('id', 'moduleName', 'moduleStyle',
        #                                                   'url', 'optValue', 'grade', 'orders', 'parent',
        #                                                   'createDate', 'updateDate').order_by('grade')
        p = Paginator(ones, page_size)
        data = p.page(page_num).object_list
        context = {
            'total': p.count,
            'rows': list(data)
        }
        return JsonResponse(context)
    except Exception as e:
        return JsonResponse({'code': 400, 'msg': '查询失败'})


@require_GET
def select_module_by_grade(request):
    try:
        grade = request.GET.get('grade')
        ones = Module.objects.values('id', 'moduleName').filter(grade=grade)
        return JsonResponse(list(ones), safe=False)
    except Exception as e:
        return JsonResponse({'code': 400, 'msg': '查询失败'})


def opt_value_has(optValue):
    flag = Module.objects.filter(optValue=optValue)
    return flag


@csrf_exempt
@require_POST
def update_module(request):
    try:
        data = request.POST.dict()
        id = data.pop('id')
        parent = data.pop('parent')
        temp_module = Module.objects.get(pk=id)
        if temp_module.optValue != data.get('optValue'):
            if opt_value_has(request.POST.get('optValue')):
                return JsonResponse({'code': 400, 'msg': '操作权限重复'})
        if parent:
            p = Module.objects.get(pk=parent)
            data['parent'] = p
        data['updateDate'] = datetime.now()
        Module.objects.filter(pk=id).update(**data)
        return JsonResponse({'code': 200, 'msg': '更新成功'})
    except Exception as e:
        return JsonResponse({'code': 400, 'msg': '更新失败'})


@csrf_exempt
@require_POST
def create_module(request):
    try:
        data = request.POST.dict()
        data.pop('id')
        parent = data.pop('parent')
        if opt_value_has(request.POST.get('optValue')):
            return JsonResponse({'code': 400, 'msg': '操作权限重复'})

templates/system/index.html
<!DOCTYPE html>
{# 导入静态资源 #}
{% load static %}
<html>
<head>
    <title>客户关系管理系统</title>
    {% include 'base.html' %}
</head>
<body class="easyui-layout">
{# 上边 #}
<div region="north" style="height: 78px;background-color: #E0ECFF;overflow: hidden;">
    <table style="padding: 5px" width="100%">
        <tr>
            <td width="50%">
                <img alt="logo" src="{% static '/images/bglogo.png' %}">
            </td>
            <td valign="bottom" align="right" width="50%">
                <strong style="font-size: 16px">欢迎【{{ request.session.username_session }}】登录</strong>
            </td>
        </tr>
    </table>
</div>
{# 中间 #}
<div region="center">
    <div class="easyui-tabs" fit="true" border="false" id="tabs">
        <div title="首页" data-options="iconCls:'icon-home'">
            <div align="center" style="padding-top: 100px">
                <font color="red" size="10">欢迎回来</font>
                                {{ request.session.user_permission }}
            </div>
        </div>
    </div>
</div>
{# 左边菜单 #}
<div region="west" style="width: 200px" title="导航菜单" split="true">
    <div class="easyui-accordion" data-options="fit:true,border:false">

        {#        {% if '10' in request.session.user_permission %}#}
        <div title="营销管理" data-options="selected:true,iconCls:'icon-yxgl'" style="padding: 10px">
            {#            {% if '1010' in request.session.user_permission %}#}
            <a href="javascript:openTab('营销机会管理', '{% url 'sales:sale_chance_index' %}','icon-yxjhgl')"
               class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-yxjhgl'" style="width: 150px">营销机会管理</a>
            {#            {% endif %}#}
            {#            {% if '1020' in request.session.user_permission %}#}
            <a href="javascript:openTab('客户开发计划','{% url 'sales:cus_dev_plan_index' %}','icon-khkfjh')"
               class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-khkfjh'" style="width: 150px">客户开发计划</a>
            {#            {% endif %}#}
        </div>
        {#        {% endif %}#}

        {#        {% if '20' in request.session.user_permission %}#}
        <div title="客户管理" data-options="iconCls:'icon-khgl'" style="padding:10px;">
            <a href="javascript:openTab('客户信息管理','{% url 'customer:customer_index' %}','icon-khxxgl')"
               class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-khxxgl'" style="width: 150px;">客户信息管理</a>
            <a href="javascript:openTab('客户流失管理','{% url 'customer:customer_loss_index' %}','icon-khlsgl')"
               class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-khlsgl'" style="width: 150px;">客户流失管理</a>
        </div>
        {#        {% endif %}#}

        {#        {% if '30' in request.session.user_permission %}#}
        <div title="服务管理" data-options="iconCls:'icon-fwgl'" style="padding:10px">
            {#            {% if '3010' in request.session.user_permission %}#}
            <a href="javascript:openTab('服务创建','{% url 'serve:serve_index' 'index' %}','icon-fwcj')"
               class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-fwcj'" style="width: 150px;">服务创建</a>
            {#            {% endif %}#}
            <a href="javascript:openTab('服务分配','{% url 'serve:serve_index' 'assign' %}','icon-fwfp')"
               class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-fwfp'" style="width: 150px;">服务分配</a>
            <a href="javascript:openTab('服务处理','{% url 'serve:serve_index' 'handler' %}','icon-fwcl')"
               class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-fwcl'" style="width: 150px;">服务处理</a>
            <a href="javascript:openTab('服务反馈','{% url 'serve:serve_index' 'feedback' %}','icon-fwfk')"
               class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-fwfk'" style="width: 150px;">服务反馈</a>
            <a href="javascript:openTab('服务归档','{% url 'serve:serve_index' 'file' %}','icon-fwgd')"
               class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-fwgd'" style="width: 150px;">服务归档</a>
        </div>
        {#        {% endif %}#}

        {#        {% if '40' in request.session.user_permission %}#}
        <div title="统计报表" data-options="iconCls:'icon-tjbb'" style="padding:10px">
            <a href="javascript:openTab('客户贡献分析','{% url 'report:report_index' 'contribute' %}','icon-khgxfx')"
               class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-khgxfx'" style="width: 150px;">客户贡献分析</a>
            <a href="javascript:openTab('客户构成分析','{% url 'report:report_index' 'composition' %}','icon-khgcfx')"
               class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-khgcfx'" style="width: 150px;">客户构成分析</a>
            <a href="javascript:openTab('客户服务分析','{% url 'report:report_index' 'serve' %}','icon-khfwfx')" class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-khfwfx'" style="width: 150px;">客户服务分析</a>
            <a href="javascript:openTab('客户流失分析','{% url 'report:report_index' 'report_loss' %}','icon-khlsfx')" class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-khlsfx'" style="width: 150px;">客户流失分析</a>
        </div>
        {#        {% endif %}#}

        {#        {% if '50' in request.session.user_permission %}#}
        <div title="基础数据管理" data-options="iconCls:'icon-jcsjgl'" style="padding:10px">
            <a href="javascript:openTab('数据字典管理','{% url 'base:datadic_index' %}','icon-sjzdgl')" class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-sjzdgl'" style="width: 150px;">数据字典管理</a>
            <a href="javascript:openTab('产品信息查询','{% url 'base:product_index' %}','icon-cpxxgl')" class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-cpxxgl'" style="width: 150px;">产品信息查询</a>
        </div>
        {#        {% endif %}#}

        {#        {% if '60' in request.session.user_permission %}#}
        <div title="系统管理" data-options="iconCls:'icon-item'" style="padding:10px">
            {#            {% if '6010' in request.session.user_permission %}#}
            <a href="javascript:openTab('用户管理','{% url 'system:user_index' %}','icon-user')" class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-user'" style="width: 150px;">用户管理</a>
            {#            {% endif %}#}
            {#            {% if '6020' in request.session.user_permission %}#}
            <a href="javascript:openTab('角色管理','{% url 'system:role_index' %}','icon-user')" class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-user'" style="width: 150px;">角色管理</a>
            {#            {% endif %}#}
            {#            {% if '6030' in request.session.user_permission %}#}
            <a href="javascript:openTab('模块管理','{% url 'system:module_index' %}','icon-user')" class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-user'" style="width: 150px;">模块管理</a>
            {#            {% endif %}#}
            {#            {% if '6040' in request.session.user_permission %}#}
            <a href="javascript:open_update_password_dialog('{{ request.session.username_session }}');"
               class="easyui-linkbutton"
               data-options="plain:true,iconCls:'icon-modifyPassword'" style="width: 150px;">修改密码</a>
            {#            {% endif %}#}
            {#            {% if '6050' in request.session.user_permission %}#}
            <a href="javascript:logout();" class="easyui-linkbutton" data-options="plain:true,iconCls:'icon-exit'"
               style="width: 150px;">安全退出</a>
            {#            {% endif %}#}
        </div>
        {#        {% endif %}#}

    </div>
</div>
{# 下边菜单 #}
<div region="south" style="height: 25px;padding: 5px;overflow: hidden;" align="center">
    版本所有 上海尚学堂 <a href="http://www.shsxt.com" target="_blank">www.shsxt.com</a>(2016-2026)
</div>

{# 修改密码对话框 #}
<div id="system_index_update_password_dialog" class="easyui-dialog">
    <form id="system_index_update_password_form" method="post">
        <input type="hidden" id="csrfmiddlewaretoken" name="csrfmiddlewaretoken"/>
        <table>
            <tr>
                <td>用户名：</td>
                <td>
                    <input id="username" name="username" readonly value="{{ request.session.username_session }}"/>
                </td>
            </tr>
            <tr>
                <td>原密码：</td>
                <td><input type="password" name="old_password" class="easyui-validatebox"
                           data-options="required:true,missingMessage:'原密码不可以为空',validType:['check_pwd_length', 'regex_check_pwd']"/>
                </td>
            </tr>
            <tr>
                <td>新密码：</td>
                <td><input type="password" name="new_password" id="new_password" class="easyui-validatebox"
                           data-options="required:true,missingMessage:'新密码不可以为空',validType:['check_pwd_length', 'regex_check_pwd']"/>
                </td>
            </tr>
            <tr>
                <td>确认密码：</td>
                <td><input type="password" class="easyui-validatebox"
                           data-options="required:true,missingMessage:'确认密码不可以为空',validType:['check_pwd_length', 'regex_check_pwd', 'eq_pwd[\'#new_password\']']"/>
                </td>
            </tr>
        </table>
    </form>
</div>
</body>
<script type="text/javascript" src="{% static '/js/validatebox_util.js' %}"></script>
<script type="text/javascript" src="{% static '/js/system/index.js' %}"></script>
</html>