base/urls.py
from django.urls import path
from base import views

app_name = 'base'

urlpatterns = [
    path('select_customer_level/', views.select_customer_level, name='select_customer_level'),
    path('datadic_index/', views.datadic_index, name='datadic_index'),
    path('select_datadic/', views.select_datadic, name='select_datadic'),
    path('select_datadic_name/', views.select_datadic_name, name='select_datadic_name'),
    path('create_datadic/', views.create_datadic, name='create_datadic'),
    path('update_datadic/', views.update_datadic, name='update_datadic'),
    path('delete_datadic/', views.delete_datadic, name='delete_datadic'),
    path('product_index/', views.product_index, name='product_index'),
    path('select_product/', views.select_product, name='select_product'),
    path('create_product/', views.create_product, name='create_product'),
    path('update_product/', views.update_product, name='update_product'),
    path('delete_product/', views.delete_product, name='delete_product'),
]

crm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('system/', include('system.urls')),
    path('sales/', include('sales.urls')),
    path('customer/', include('customer.urls')),
    path('base/', include('base.urls')),
    path('serve/', include('serve.urls')),
    path('report/', include('report.urls'))
]

customer/urls.py
from django.urls import path
from customer import views

app_name = 'customer'

urlpatterns = [
    path('select_cname_and_lname_and_uname/', views.select_cname_and_lname_and_uname,
         name='select_cname_and_lname_and_uname'),
    path('select_link_phone_by_id/', views.select_link_phone_by_id, name='select_link_phone_by_id'),
    path('customer_index/', views.customer_index, name='customer_index'),
    path('select_customer_list/', views.select_customer_list, name='select_customer_list'),
    path('create_customer/', views.create_customer, name='create_customer'),
    path('select_customer_by_id/', views.select_customer_by_id, name='select_customer_by_id'),
    path('update_customer/', views.update_customer, name='update_customer'),
    path('delete_customer/', views.delete_customer, name='delete_customer'),
    path('linkman_index/', views.linkman_index, name='linkman_index'),
    path('select_linkman_by_customer_id/<int:id>/', views.select_linkman_by_customer_id,
         name='select_linkman_by_customer_id'),
    path('create_linkman/<int:id>/', views.create_linkman, name='create_linkman'),
    path('update_linkman/', views.update_linkman, name='update_linkman'),
    path('delete_linkman/', views.delete_linkman, name='delete_linkman'),
    path('contact_index/', views.contact_index, name='contact_index'),
    path('select_contact_by_customer_id/<int:id>/', views.select_contact_by_customer_id,
         name='select_contact_by_customer_id'),
    path('create_contact/<int:id>/', views.create_contact, name='create_contact'),
    path('update_contact/', views.update_contact, name='update_contact'),
    path('delete_contact/', views.delete_contact, name='delete_contact'),
    path('order_index/', views.order_index, name='order_index'),
    path('select_order_by_customer_id/<int:id>/', views.select_order_by_customer_id,
         name='select_order_by_customer_id'),
    path('select_order_by_id/', views.select_order_by_id, name='select_order_by_id'),
    path('select_order_detail_by_order_id/<int:id>/', views.select_order_detail_by_order_id,
         name='select_order_detail_by_order_id'),
    path('customer_loss_index/', views.customer_loss_index, name='customer_loss_index'),
    path('select_loss/', views.select_loss, name='select_loss'),
    path('reprieve_index/', views.reprieve_index, name='reprieve_index'),
    path('select_reprieve_by_loss_id/<int:id>/', views.select_reprieve_by_loss_id, name='select_reprieve_by_loss_id'),
    path('create_reprieve/<int:id>/', views.create_reprieve, name='create_reprieve'),
    path('update_reprieve/', views.update_reprieve, name='update_reprieve'),
    path('delete_reprieve/', views.delete_reprieve, name='delete_reprieve'),
    path('ok_reprieve/', views.ok_reprieve, name='ok_reprieve'),
    path('select_customer_name/', views.select_customer_name, name='select_customer_name')
]

serve/urls.py
from django.urls import path
from serve import views

app_name = 'serve'

urlpatterns = [
    path('serve_index/<str:serve_type>/', views.serve_index, name='serve_index'),
    # path('serve_assign/', views.serve_assign, name='serve_assign'),
    # path('serve_handler/', views.serve_handler, name='serve_handler'),
    # path('serve_feedback/', views.serve_feedback, name='serve_feedback'),
    # path('serve_file/', views.serve_file, name='serve_file'),
    path('create_serve/', views.create_serve, name='create_serve'),
    path('select_serve/', views.select_serve, name='select_serve'),
    path('update_serve/', views.update_serve, name='update_serve'),
]

system/urls.py
from django.urls import path
from system import views

app_name = 'system'

urlpatterns = [
    path('login_register/', views.login_register, name='login_register'),
    path('unique_username/', views.unique_username, name='unique_username'),
    path('unique_email/', views.unique_email, name='unique_email'),
    path('send_email/', views.send_email, name='send_email'),
    path('active_account/', views.active_account, name='active_account'),
    path('login_user/', views.login_user, name='login_user'),
    path('index/', views.index, name='index'),
    path('update_password/', views.update_password, name='update_password'),
    path('logout/', views.logout, name='logout'),
    path('select_customer_manager/', views.select_customer_manager, name='select_customer_manager'),
    path('module_index/', views.module_index, name='module_index'),
    path('select_module_by_grade/', views.select_module_by_grade, name='select_module_by_grade'),
    path('update_module/', views.update_module, name='update_module'),
    path('select_module/', views.select_module, name='select_module'),
    path('create_module/', views.create_module, name='create_module'),
    path('delete_module/', views.delete_module, name='delete_module'),
    path('role_index/', views.role_index, name='role_index'),
    path('update_role/', views.update_role, name='update_role'),
    path('select_role/', views.select_role, name='select_role'),
    path('create_role/', views.create_role, name='create_role'),
    path('delete_role/', views.delete_role, name='delete_role'),
    path('role_module_index/', views.role_module_index, name='role_module_index'),
    path('role_relate_module/', views.role_relate_module, name='role_relate_module'),
    path('role_relate_module/', views.role_relate_module, name='role_relate_module'),
    path('user_index/', views.user_index, name='user_index'),
    path('select_user/', views.select_user, name='select_user'),
    path('select_role_for_user/', views.select_role_for_user, name='select_role_for_user'),
    path('create_user/', views.create_user, name='create_user'),
    path('select_role_by_userid/', views.select_role_by_userid, name='select_role_by_userid'),
    path('update_user/', views.update_user, name='update_user'),
    path('delete_user/', views.delete_user, name='delete_user'),
]

serve/models.py
from django.db import models


class ModelManager(models.Manager):

    def get_queryset(self):
        return super(ModelManager, self).get_queryset().filter(isValid=1)


# 服务模型
class CustomerServe(models.Model):
    # 服务类型 咨询/建议/投诉
    serveType = models.CharField(db_column='serve_type', max_length=30)
    # 概要
    overview = models.CharField(db_column='overview', max_length=500)
    # 客户
    customer = models.CharField(db_column='customer', max_length=30)
    # 新创建/已分配/已处理/已归档
    state = models.CharField(db_column='state', max_length=10)
    # 服务请求
    serviceRequest = models.CharField(db_column='service_request', max_length=500)
    # 创建人
    createPeople = models.CharField(db_column='create_people', max_length=100)
    # 分配人
    assigner = models.CharField(db_column='assigner', max_length=100)
    # 分配日期
    assignTime = models.DateTimeField(db_column='assign_time')
    # 服务处理
    serviceProce = models.CharField(db_column='service_proce', max_length=500)
    # 服务处理人
    serviceProcePeople = models.CharField(db_column='service_proce_people', max_length=50)
    # 服务处理日期
    serviceProceTime = models.DateTimeField(db_column='service_proce_time')
    # 服务处理结果
    serviceProceResult = models.CharField(db_column='service_proce_result', max_length=500)

    # 客户满意度
    myd = models.CharField(db_column='myd', max_length=50)
    isValid = models.IntegerField(db_column='is_valid', default=1)
    createDate = models.DateTimeField(db_column='create_date', auto_now_add=True)
    updateDate = models.DateTimeField(db_column='update_date')
    objects = ModelManager()

    class Meta:
        db_table = 't_customer_serve'

serve/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST, require_GET
from django.db.models import Q
from datetime import datetime

from .models import CustomerServe


@require_GET
def serve_index(request, serve_type):
    return render(request, 'serve/serve_{}.html'.format(serve_type))


@csrf_exempt
@require_POST
def create_serve(request):
    try:
        data = request.POST.dict()
        data.pop('csrfmiddlewaretoken')
        data['state'] = '新创建'
        data['createPeople'] = request.session.get('username_session')
        CustomerServe.objects.create(**data)
        return JsonResponse({'code': 200, 'msg': '创建成功'})
    except Exception as e:
        return JsonResponse({'code': 400, 'msg': '创建失败'})


# def serve_assign(request):
#     return render(request, 'serve/serve_assign.html')
#
#
# def serve_handler(request):
#     return render(request, 'serve/serve_handler.html')
#
#
# def serve_feedback(request):
#     return render(request, 'serve/serve_feedback.html')
#
#
# def serve_file(request):
#     return render(request, 'serve/serve_file.html')


@require_GET
def select_serve(request):
    try:
        page_num = request.GET.get('page')
        page_size = request.GET.get('rows')

        customer = request.GET.get('customer')
        overview = request.GET.get('overview')
        serveType = request.GET.get('serveType')
        createTimefrom = request.GET.get('createTimefrom')
        createDateto = request.GET.get('createDateto')

        state = request.GET.get('state')

        ones = CustomerServe.objects.values().filter(state=state).order_by('-id')

        if customer:
            ones = ones.filter(customer__contains=customer)
        if overview:
            ones = ones.filter(overview__contains=overview)
        if serveType and '请选择服务类型' != serveType:
            ones = ones.filter(serveType=serveType)
        if createTimefrom:
            ones = ones.filter(createDate__gte=createTimefrom)
        if createDateto:
            ones = ones.filter(createDate__lte=createDateto)

        p = Paginator(ones, page_size)
        data = p.page(page_num).object_list

        context = {
            'total': p.count,
            'rows': list(data)
        }
        return JsonResponse(context)
    except Exception as e:
        return
        return JsonResponse({'code': 400, 'msg': '查询失败'})


@csrf_exempt
@require_POST
def update_serve(request):
    try:
        data = request.POST.dict()
        data.pop('csrfmiddlewaretoken')
        id = data.pop('id')
        state = data['state']
        if state == '已分配':
            data['assignTime'] = datetime.now()
        if state == '已处理':
            data['serviceProceTime'] = datetime.now()
        data['updateDate'] = datetime.now()
        CustomerServe.objects.filter(pk=id).update(**data)
        return JsonResponse({'code': 200, 'msg': '更新成功'})
    except Exception as e:
        return JsonResponse({'code': 400, 'msg': '更新失败'})

templates/serve/serve_assign.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>服务分配</title>
    <link rel="stylesheet" type="text/css" href="{% static '/jquery-easyui-1.3.3/themes/default/easyui.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/jquery-easyui-1.3.3/themes/icon.css' %}">
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/jquery.easyui.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/locale/easyui-lang-zh_CN.js' %}"></script>
    <script type="text/javascript" src="{% static '/js/jquery.cookie.js' %}"></script>
    <script type="text/javascript" src="{% static '/js/ueditor/utf8-jsp/ueditor.config.js' %}"></script>
    <script type="text/javascript" src="{% static '/js/ueditor/utf8-jsp/ueditor.all.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/js/ueditor/utf8-jsp/lang/zh-cn/zh-cn.js' %}"></script>
</head>
<body>
<table id="dg" class="easyui-datagrid" title="服务分配管理"
       data-options="rownumbers:true,pagination:true,fit:true,
			    pageList:[10,15,20,30,40,50],toolbar: '#tb',
                url:'{% url 'serve:select_serve' %}?state=新创建',method:'get'">
    <thead>
    <tr>
        <th data-options="field:'id',checkbox:true"></th>
        <th data-options="field:'customer',width:200">客户名称</th>
        <th data-options="field:'overview',width:500">概要</th>
        <th data-options="field:'serveType',width:100">服务类型</th>
        <th data-options="field:'createPeople',width:120">创建人</th>
        <th data-options="field:'createDate',width:160,formatter:formatter_datetime">创建时间</th>
    </tr>
    </thead>
</table>

{# 工具栏 #}
<div id="tb">
    <a onclick="open_serve_dialog();" class="easyui-linkbutton" data-options="iconCls:'icon-fwfp',plain:true">分配</a>
</div>

{# 分配服务对话框 #}
<div id="dialog" class="easyui-dialog" iconCls="icon-fwfp">
    <br/><br/>
    <form id="fm" method="post">
        {% csrf_token %}
        <input type="hidden" name="id"/>
        <input type="hidden" name="state" value="已分配"/>
        <label style="padding-right: 12px;padding-left: 30px">服务类型</label>
        <input id="serveType" name="serveType" readonly/>
        <label style="padding-right: 10px;padding-left: 10px">客户名称</label>
        <input id="customer" name="customer" readonly/><br/><br/>
        <label style="padding-right: 38px;padding-left: 30px">概要</label>
        <input id="overview" name="overview" style="width: 414px" readonly/><br/><br/>
        <label style="padding-right: 14px;padding-left: 30px">服务请求</label>
        <textarea id="serviceRequest" name="serviceRequest" readonly style="width: 414px;height: 100px"></textarea><br/><br/>
        <label style="padding-right: 30px;padding-left: 30px">创建人</label><input readonly id="createPeople" name="createPeople"/>
        <label style="padding-right: 20px;padding-left: 10px">创建时间</label><input readonly id="createDate" name="createDate"/><br/><br/>
        <label style="padding-right: 30px;padding-left: 30px">分配人</label>
        <input id="assigner" name="assigner" class="easyui-combobox"
               data-options="valueField:'username',textField:'username',value:'请选分配人',editable:false,
               url:'{% url 'system:select_customer_manager' %}',method:'get'">
    </form>
</div>
<script type="text/javascript" src="{% static '/js/serve/serve_common.js' %}"></script>
<script type="text/javascript" src="{% static '/js/serve/serve_assign.js' %}"></script>
</body>
</html>

templates/serve/serve_file.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>服务归档</title>
    <link rel="stylesheet" type="text/css" href="{% static '/jquery-easyui-1.3.3/themes/default/easyui.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/jquery-easyui-1.3.3/themes/icon.css' %}">
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/jquery.easyui.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/locale/easyui-lang-zh_CN.js' %}"></script>
    <script type="text/javascript" src="{% static '/js/jquery.cookie.js' %}"></script>
</head>
<body>
<table id="dg" class="easyui-datagrid" title="服务归档管理"
       data-options="rownumbers:true,pagination:true,fit:true,
			    pageList:[10,15,20,30,40,50],toolbar: '#tb',
                url:'{% url 'serve:select_serve' %}?state=已归档',method:'get'">
    <thead>
    <tr>
        <th data-options="field:'id',checkbox:true"></th>
        <th data-options="field:'customer',width:200">客户名称</th>
        <th data-options="field:'overview',width:500">概要</th>
        <th data-options="field:'serveType',width:100">服务类型</th>
        <th data-options="field:'createPeople',width:120">创建人</th>
        <th data-options="field:'createDate',width:160,formatter:formatter_datetime">创建时间</th>
    </tr>
    </thead>
</table>

{# 工具栏 #}
<div id="tb">
    <a onclick="open_serve_dialog();" class="easyui-linkbutton"
       data-options="iconCls:'icon-fwgd',plain:true">查看客户服务详情</a>
    <div>
        客户名称&nbsp;&nbsp;<input id="s_customer" onkeydown="if (event.keyCode==13) select_params_serve();"/>
        &nbsp;&nbsp;概要&nbsp;&nbsp;<input id="s_overview" onkeydown="if (event.keyCode==13) select_params_serve();"/>
        &nbsp;&nbsp;服务类型&nbsp;&nbsp;
        <input id="s_serveType" name="s_serveType" class="easyui-combobox" style="width: 120px"
               data-options="valueField:'dataDicValue',textField:'dataDicValue',value:'请选择服务类型',editable:false,
           url:'{% url 'base:select_customer_level' %}?dic_name=服务类型',method:'get'">
        &nbsp;创建日期：&nbsp;<input type="text" id="s_createDatefrom" class="easyui-datebox"
                                editable="true"/>&nbsp;-&nbsp;<input type="text" id="s_createDateto"
                                                                     class="easyui-datebox" editable="true"/>
        <a id="btn" onclick="select_params_serve();" class="easyui-linkbutton"
           data-options="iconCls:'icon-search'">查询</a>
    </div>
</div>

{# 归档查看客户服务详情框 #}
<div id="dialog" class="easyui-dialog" iconCls="icon-fwgd">
    <br/>
    <form id="fm" method="post">
        <input type="hidden" id="csrfmiddlewaretoken" name="csrfmiddlewaretoken"/>
        <input type="hidden" name="id"/>
        <input type="hidden" name="state" value="已归档"/>
        <label style="padding-right: 12px;padding-left: 30px">服务类型</label>
        <input id="serveType" name="serveType" readonly/>
        <label style="padding-right: 10px;padding-left: 10px">客户名称</label>
        <input id="customer" name="customer" readonly/><br/><br/>
        <label style="padding-right: 38px;padding-left: 30px">概要</label>
        <input id="overview" name="overview" style="width: 414px" readonly/><br/><br/>
        <label style="padding-right: 14px;padding-left: 30px">服务请求</label>
        <textarea id="serviceRequest" name="serviceRequest" readonly
                  style="width: 414px;height: 50px"></textarea><br/><br/>
        <label style="padding-right: 30px;padding-left: 30px">创建人</label><input readonly id="createPeople"
                                                                                name="createPeople"/>
        <label style="padding-right: 20px;padding-left: 10px">创建时间</label><input readonly id="createDate"
                                                                                 name="createDate"/><br/><br/>
        <label style="padding-right: 30px;padding-left: 30px">分配人</label>
        <input id="assigner" name="assigner" readonly/>
        <label style="padding-right: 20px;padding-left: 10px">分配时间</label><input readonly id="assignTime"
                                                                                 name="assignTime"/><br/><br/>
        <label style="padding-right: 14px;padding-left: 30px">服务处理</label>
        <textarea readonly id="serviceProce" name="serviceProce" style="width: 414px;height: 50px"
                  class="easyui-validatebox" data-options="required:true"></textarea><br/><br/>
        <label style="padding-right: 25px;padding-left: 30px">处理人</label>
        <input type="hidden" id="session_username" value="{{ request.session.username_session }}"/>
        <input readonly id="serviceProcePeople" name="serviceProcePeople"/>
        <label style="padding-right: 20px;padding-left: 10px">处理时间</label><input readonly id="serviceProceTime"
                                                                                 name="serviceProceTime"/><br/><br/>
        <label style="padding-right: 25px;padding-left: 30px">处理结果</label><input readonly id="serviceProceResult"
                                                                                 name="serviceProceResult"
                                                                                 class="easyui-validatebox"
                                                                                 data-options="required:true"/>
        <label style="padding-right: 25px;padding-left: 30px">客户满意度</label><input readonly id="myd" name="myd"/>
    </form>
</div>
<script type="text/javascript" src="{% static '/js/serve/serve_file.js' %}"></script>
</body>
</html>

templates/serve/serve_handler.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>服务处理</title>
    <link rel="stylesheet" type="text/css" href="{% static '/jquery-easyui-1.3.3/themes/default/easyui.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/jquery-easyui-1.3.3/themes/icon.css' %}">
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/jquery.easyui.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/locale/easyui-lang-zh_CN.js' %}"></script>
    <script type="text/javascript" src="{% static '/js/jquery.cookie.js' %}"></script>
</head>
<body>
<table id="dg" class="easyui-datagrid" title="服务处理管理"
       data-options="rownumbers:true,pagination:true,fit:true,
			    pageList:[10,15,20,30,40,50],toolbar: '#tb',
                url:'{% url 'serve:select_serve' %}?state=已分配',method:'get'">
    <thead>
    <tr>
        <th data-options="field:'id',checkbox:true"></th>
        <th data-options="field:'customer',width:200">客户名称</th>
        <th data-options="field:'overview',width:300">概要</th>
        <th data-options="field:'serveType',width:100">服务类型</th>
        <th data-options="field:'createPeople',width:120">创建人</th>
        <th data-options="field:'createDate',width:150,formatter:formatter_datetime">创建时间</th>
        <th data-options="field:'assigner',width:120">分配人</th>
        <th data-options="field:'assignTime',width:150,formatter:formatter_datetime">分配时间</th>
    </tr>
    </thead>
</table>

{# 工具栏 #}
<div id="tb">
    <a onclick="open_serve_dialog();" class="easyui-linkbutton" data-options="iconCls:'icon-fwcl',plain:true">处理</a>
</div>

{# 分配处理对话框 #}
<div id="dialog" class="easyui-dialog" iconCls="icon-fwcl">
    <br/>
    <form id="fm" method="post">
        {% csrf_token %}
        <input type="hidden" name="id"/>
        <input type="hidden" name="state" value="已处理"/>
        <label style="padding-right: 12px;padding-left: 30px">服务类型</label>
        <input id="serveType" name="serveType" readonly/>
        <label style="padding-right: 10px;padding-left: 10px">客户名称</label>
        <input id="customer" name="customer" readonly/><br/><br/>
        <label style="padding-right: 38px;padding-left: 30px">概要</label>
        <input id="overview" name="overview" style="width: 414px" readonly/><br/><br/>
        <label style="padding-right: 14px;padding-left: 30px">服务请求</label>
        <textarea id="serviceRequest" name="serviceRequest" readonly style="width: 414px;height: 60px"></textarea><br/><br/>
        <label style="padding-right: 30px;padding-left: 30px">创建人</label><input readonly id="createPeople" name="createPeople"/>
        <label style="padding-right: 20px;padding-left: 10px">创建时间</label><input readonly id="createDate" name="createDate"/><br/><br/>
        <label style="padding-right: 30px;padding-left: 30px">分配人</label>
        <input id="assigner" name="assigner" class="easyui-combobox"
               data-options="valueField:'username',textField:'username',value:'请选分配人',editable:false,
               url:'{% url 'system:select_customer_manager' %}',method:'get'"><br/><br/>
        <label style="padding-right: 14px;padding-left: 30px">服务处理</label>
        <textarea id="serviceProce" name="serviceProce" style="width: 414px;height: 60px" class="easyui-validatebox" data-options="required:true"></textarea><br/><br/>
        <label style="padding-right: 25px;padding-left: 30px">处理人</label>
        <input type="hidden" id="session_username" value="{{ request.session.username_session }}"/>
        <input readonly id="serviceProcePeople" name="serviceProcePeople"/>
    </form>
</div>
<script type="text/javascript" src="{% static '/js/serve/serve_common.js' %}"></script>
<script type="text/javascript" src="{% static '/js/serve/serve_handler.js' %}"></script>
</body>
</html>

templates/serve/serve_index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>服务创建</title>
    <link rel="stylesheet" type="text/css" href="{% static '/jquery-easyui-1.3.3/themes/default/easyui.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/jquery-easyui-1.3.3/themes/icon.css' %}">
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/jquery.easyui.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/jquery-easyui-1.3.3/locale/easyui-lang-zh_CN.js' %}"></script>
    <script type="text/javascript" src="{% static '/js/ueditor/utf8-jsp/ueditor.config.js' %}"></script>
    <script type="text/javascript" src="{% static '/js/ueditor/utf8-jsp/ueditor.all.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/js/ueditor/utf8-jsp/lang/zh-cn/zh-cn.js' %}"></script>
</head>
<body>
<div id="p" class="easyui-panel" title="服务创建"
     style="width:auto;height:500px;padding:10px;background:#fafafa;"
     data-options="iconCls:'icon-save',closable:true,
                collapsible:true,minimizable:false,closable:false">
    <br/><br/>
    <form id="fm" method="post">
        {% csrf_token %}
        <label style="padding-right: 10px;padding-left: 30px">服务类型</label>
        <input id="serveType" name="serveType" class="easyui-combobox"
               data-options="valueField:'dataDicValue',textField:'dataDicValue',value:'请选择服务类型',editable:false,
           url:'{% url 'base:select_customer_level' %}?dic_name=服务类型',method:'get'">
        <label style="padding-right: 10px;padding-left: 10px">客户名称</label>
        <input id="customer" name="customer" class="easyui-combobox"
               data-options="valueField:'name',textField:'name',value:'请选客户名称',editable:false,
           url:'{% url 'customer:select_customer_name' %}',method:'get'"><br/><br/>
        <label style="padding-right: 38px;padding-left: 30px">概要</label>
        <input id="overview" name="overview" class="easyui-validatebox" data-options="required:true"
               style="width: 414px"/><br/><br/>
        <label style="padding-right: 14px;padding-left: 30px;">服务请求</label>
        <div style="position: relative;top: -10px">
            <textarea id="serviceRequest" name="serviceRequest" style="padding-left: 100px"></textarea>
        </div>
    </form>

    <div style="padding-right: 60px">
        <a onclick="reset();" style="float: right" class="easyui-linkbutton" data-options="iconCls:'icon-undo'">重置</a>
        <a id="save_btn" onclick="save_serve();" style="float: right" class="easyui-linkbutton"
           data-options="iconCls:'icon-save'">保存</a>
    </div>
</div>
<script type="text/javascript" src="{% static '/js/serve/serve_index.js' %}"></script>
</body>
</html>